export type AppState =
  | ""
  | "sign-in"
  | "sign-up"
  | "forgot-password"
  | "reset-password-email-sent"
  | "home"
  | "discover"
  | "movies"
  | "tv-shows"
  | "details"
  | "search"
  | "watchlist"
  | "watchlist-movies"
  | "watchlist-tv-shows"
  | "profile"
  | "not-found"
  | "error";
