export const VALID_MEDIA_SHELF_CATEGORIES = [
  'top-rated-films',
  'top-rated-shows',
  'award-winning-cinema',
  'timeless-classics',
  'boxoffice-legends',
  'trending-movies',
  'drama',
  'action-adventure',
  'crime-thriller',
  'comedy',
  'bollywood-hits',
  'horror',
  'romance',
  'telugu-originals',
  'science-fiction',
  'tamil-malayalam-cinema',
  'documentary',
  'korean-cinema',
  'trending-tv-shows',
  'popular',
  'critically-acclaimed',
  'comedy-sitcom',
  'sci-fi-fantasy',
  'mystery-suspense',
  'anime',
  'indian-originals',
] as const;

export type mediaShelfCategory = (typeof VALID_MEDIA_SHELF_CATEGORIES)[number];
