services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8000:5000'
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
    command: npm run dev:picturehouse

    develop:
      watch:
        - action: sync
          path: ./client
          target: /app/client
          ignore:
            - node_modules/

        - action: sync
          path: ./server
          target: /app/server
          ignore:
            - node_modules/

        - action: rebuild
          path: ./package.json
